name: Test

on:
  push:
  pull_request:
  schedule:
    # Weekly, at 5:45 AM on Friday (somewhat randomly chosen).
    - cron: '45 5 * * 5'
  workflow_dispatch:


jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        platform: [x86, x64]
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: '${{ matrix.os }}'
    name: 'Test: ${{ matrix.os }} / ${{ matrix.platform }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up GCC
        uses: ./
        with:
          platform: '${{ matrix.platform }}'
          cc: 1
      - name: Build foo.exe
        uses: ./.github/actions/build-foo
      - name: Run foo.exe
        uses: ./.github/actions/run-foo
      - name: Check symlinks
        uses: ./.github/actions/check-cc

  versions:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        version: [9, 10, 11, 12, 13, 14, 15]
        exclude:
          - {os: ubuntu-22.04, version: 14}
          - {os: ubuntu-22.04, version: 15}
          - {os: ubuntu-24.04, version: 15}
    runs-on: '${{ matrix.os }}'
    name: 'Version: ${{ matrix.os }} / ${{ matrix.version }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up GCC
        uses: ./
        with:
          version: '${{ matrix.version }}'
          platform: '${{ matrix.platform }}'
          cc: 1
      - name: Build foo.exe
        uses: ./.github/actions/build-foo
        with:
          version: '${{ matrix.version }}'
      - name: Run foo.exe
        uses: ./.github/actions/run-foo
      - name: Check symlinks
        uses: ./.github/actions/check-cc
        with:
          version: '${{ matrix.version }}'

  cygwin:
    strategy:
      fail-fast: false
      matrix:
        hardlinks: [0, 1]
    runs-on: windows-latest
    name: 'Cygwin: hardlinks${{ matrix.hardlinks }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clean up PATH
        uses: egor-tensin/cleanup-path@v3
      - name: Install Cygwin
        uses: egor-tensin/setup-cygwin@v4
      - name: Set up GCC
        uses: ./
        with:
          cygwin: 1
          cc: 1
          hardlinks: '${{ matrix.hardlinks }}'
      - name: Build foo.exe
        uses: ./.github/actions/build-foo
        if: matrix.hardlinks
      - name: Build foo.exe
        uses: ./.github/actions/build-foo-cygwin
        if: '!matrix.hardlinks'
      - name: Run foo.exe
        uses: ./.github/actions/run-foo
      - name: Check symlinks
        uses: ./.github/actions/check-cc
        if: matrix.hardlinks
      - name: Check symlinks
        uses: ./.github/actions/check-cc-cygwin
        if: '!matrix.hardlinks'
